# Server Port
server.port=8080

# Spring Data JPA & H2 Database (Đã tắt)
# spring.datasource.url=jdbc:h2:file:./data/pricetracker;DB_CLOSE_DELAY=-1;NON_KEYWORDS=KEY
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=password
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console

# Cấu hình Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Cấu hình GitHub Models API — đọc từ biến môi trường GITHUB_MODELS_TOKEN
github.models.token=${GITHUB_MODELS_TOKEN}
github.models.model-name=${GITHUB_MODELS_MODEL_NAME:gpt-4o}

# Cấu hình CORS
# cors.allowed-origins=*

# --- CẤU HÌNH POSTGRESQL --- đọc từ biến môi trường
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/price_tracker}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:123456}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
